name: Reactions Counter
description:
  Counts reactions on GitHub Issues and updates a corresponding GitHub Project
  with the count
author: David Finol

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: red

# Define your inputs here.
inputs:
  project-url:
    description: The URL of the GitHub Project to update
    required: true
  github-token:
    description: The GitHub token to use
    required: true
  field-name:
    description: The name of the field to update
    required: true

# Define your outputs here.
outputs:
  status:
    description: The status of the action

runs:
  using: node20
  main: dist/index.js
